### ISSUE TITLE
Inconsistencies in EASE-WF

### ISSUE THREAD

**Issue by daniel86** [ease-crc/ease_ontology#67]
Here is what Hermit reports:

## Classes equivalent to http://www.w3.org/2002/07/owl#Nothing

  - http://www.ease-crc.org/ont/EASE-WF.owl#ConditionalSuccedence
  - http://www.ease-crc.org/ont/EASE-WF.owl#Succedence
  - http://www.ease-crc.org/ont/EASE-WF.owl#TaskInvocation
  - http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#Project
  - http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#Workflow
  - http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#WorkflowExecution
  - http://www.ontologydesignpatterns.org/ont/dul/IOLite.owl#LinguisticFunction
  - http://www.w3.org/2002/07/owl#Nothing

## Subclasses of http://www.w3.org/2002/07/owl#Nothing

No issues detected.

## Object properties equivalent to http://www.w3.org/2002/07/owl#bottomObjectProperty

  - ObjectInverseOf(http://www.ease-crc.org/ont/EASE-WF.owl#hasFirstStep)
  - ObjectInverseOf(http://www.ease-crc.org/ont/EASE-WF.owl#hasPredecessor)
  - ObjectInverseOf(http://www.ease-crc.org/ont/EASE-WF.owl#hasStep)
  - ObjectInverseOf(http://www.ease-crc.org/ont/EASE-WF.owl#hasSuccedence)
  - ObjectInverseOf(http://www.ease-crc.org/ont/EASE-WF.owl#hasSuccessor)
  - http://www.w3.org/2002/07/owl#bottomObjectProperty

## Subproperties of http://www.w3.org/2002/07/owl#bottomObjectProperty

No issues detected.

## Unhandled subsumptions

No issues detected.

**Comment by daniel86** [comment]
My guess is that it is caused by asserting that *hasPart* is transitive in EASE-WF.

**Comment by mpomarlan** [comment]
It's a bit more complex than that (and hasPart should be transitive in DUL too AFAIK).

ConditionalSuccedence and Succedence are empty because they must connect to a TaskInvocation, which is empty because it is a subclass of Workflow, which is empty. WorkflowExecution is empty because it must satisfy some Workflow, which is empty.

I'll come back in a moment as to why Workflow is empty.

**Comment by mpomarlan** [comment]
Workflow is empty because:

Because it is a Plan, a Workflow must be isPlanFor some Task, and Tasks are objects. Because isPlanFor is a subproperty of describes, it means a Workflow must describe some Object (a Task, to be more specific).

A Workflow also 'defines Task' some Task, which is the same as saying that there will be a Task connected by 'is task defined in' to the Workflow.

However, 'is task defined in' o describes is a subproperty of 'is task afforded by'. As a reminder:

Task -(is task defined in)-> Workflow -(describes)-> Task
====>
Task -('is task afforded by')-> Task

'is task afforded by' has range Disposition, which is a Quality, which is disjoint from Object, so it is also disjoint from Task.

**Comment by mpomarlan** [comment]
The argument for Project being empty is similar.

It is a subset of Plan, so isPlanFor some Task, aka describes some Task. But Projects also define a Task, and then the Task -('is task afforded by')-> Task pattern happens again, resulting in the same inconsistency.

**Comment by mpomarlan** [comment]
LinguisticFunction being empty is analogous.

LinguisticFunction is defined in some LinguisticTheory, which means it describes some (isComponentOf some NaturalLanguage), which means a LinguisticTheory describes some part of a NaturalLanguage, which has only Object parts.

So we must have

LinguisticFunction -(is defined in)-> LinguisticTheory -(describes)-> Object

However, 'is defined in' o describes subproperty of 'is concept afforded by' which has range Disposition, a Quality, and Qualities are disjoint with Objects.

**Comment by mpomarlan** [comment]
hasPredecessor, hasSuccessor, hasSuccedence are bottom properties because their domains and ranges are empty.

hasStep, hasNextStep are bottom properties because their domain is empty.

**Comment by mpomarlan** [comment]
Therefore, the source of the inconsistencies can be traced to these two axioms:

'is task defined in' o describes is a subproperty of 'is task afforded by'
'is defined in' o describes subproperty of 'is concept afforded by'

**Comment by mpomarlan** [comment]
Essentially, three approaches possible: 

1) replace "describes" there with something more specialized, because describes is an extremely generic property that can link Descriptions to any other kind of Entity, and this shows that extending the ontology will be extremely fragile if we have to pay attention to such interactions between properties.

2) replace 'is task defined in', 'is defined in' in the property chain definitions. Potentially very easy, because the idea is that they link a Task or Concept to a particular kind of Description, an Affordance. Probably the way to go: 'is task defined in Affordance', 'is defined in Affordance'.

3) replace 'is task defined in', 'is defined in' in the definitions of Plan, Workflow etc. Probably impossible given the DUL foundation.

Perhaps the least violence, especially to our Affordance model, can be done using solution 2. Imo, the best available choice.

**Comment by daniel86** [comment]
> Workflow is empty because:
> 
> Because it is a Plan, a Workflow must be isPlanFor some Task, and Tasks are objects. Because isPlanFor is a subproperty of describes, it means a Workflow must describe some Object (a Task, to be more specific).
> 
> A Workflow also 'defines Task' some Task, which is the same as saying that there will be a Task connected by 'is task defined in' to the Workflow.
> 
> However, 'is task defined in' o describes is a subproperty of 'is task afforded by'. As a reminder:
> 
> Task -(is task defined in)-> Workflow -(describes)-> Task
> ====>
> Task -('is task afforded by')-> Task
> 
> 'is task afforded by' has range Disposition, which is a Quality, which is disjoint from Object, so it is also disjoint from Task.

hmm... *describes* has range *Entity* -- so it should be Ok that an *Affordance* (a *Description*) describes a *Disposition* (a quality).
*Tasks* may further be defined *only* in *Descriptions* -- so it is fine that tasks are defined in an *Affordance*.

**Comment by mpomarlan** [comment]
The issue is not that 'describes' connects to a Quality. The issue is that the definition of Workflow implies an 'is task afforded by' between a Task and a Task.

**Comment by daniel86** [comment]
> The issue is not that 'describes' connects to a Quality. The issue is that the definition of Workflow implies an 'is task afforded by' between a Task and a Task.

ok, I see. It is caused because *Plan isPlanFor some Task* which means there is at least one task described by a Plan. But the reasoner thinks that any chain *is-task-defined-in o describes* must have range Disposition because we have defined is-task-afforded-by?

**Comment by mpomarlan** [comment]
Indeed, that's what's happening.

Probably the least effort we can do to correct this is to nudge the definitions of 'is task afforded by', 'is concept afforded by' towards using more specific versions of 'is task defined in' and 'is defined in'.

**Comment by daniel86** [comment]
I still have to swallow that implication of *is-task-afforded-by*.

But, yes, I agree with you that introducing more specific properties might be best.

**Comment by daniel86** [comment]
fixed in #71
